import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { renderer } from './renderer'

type Track = { title: string; url: string }
type Playlist = { name: string; tracks: Track[] }
type PlaylistData = { playlists: Playlist[] }

type ApiConfig = {
  id: string
  name: string
  type: 'playlist'
  url: string
  createdAt: string
}
type ApiRegistry = { apis: ApiConfig[] }

const HEALTH_METRICS = ['weight', 'body_fat', 'active_energy', 'exercise_min', 'steps'] as const
type HealthMetric = (typeof HEALTH_METRICS)[number]
type HealthDay = { date: string } & Partial<Record<HealthMetric, number>>
const MAX_HEALTH_DAYS_PER_REQUEST = 400
const HEALTH_PUBLIC_DAYS = 30

// CloudflareBindings is auto-generated by `wrangler types`.
// PLAYLIST_AUTH_TOKEN / HEALTH_AUTH_TOKEN are Workers Secrets — set via `wrangler secret put`.
type AppBindings = CloudflareBindings & { PLAYLIST_AUTH_TOKEN?: string; HEALTH_AUTH_TOKEN?: string }

const app = new Hono<{ Bindings: AppBindings }>()

app.use(renderer)
app.use('*', cors({ origin: '*', allowMethods: ['GET', 'PUT', 'POST', 'DELETE', 'OPTIONS'] }))

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 6)
}

function authed(secret: string | undefined, auth: string | null | undefined): boolean {
  return !!secret && auth === `Bearer ${secret}`
}

// ── System routes ─────────────────────────────────────────────────

app.get('/', (c) => c.render(<h1>Hello!</h1>))
app.get('/status', (c) => c.json({ message: 'Hello VRChat', updatedAt: new Date().toISOString() }))

// ── Admin routes (auth required) ──────────────────────────────────

app.get('/admin/apis', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  let registry = await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')

  if (!registry) {
    // First access: auto-migrate legacy playlist data if it exists
    const legacyData = await c.env.PLAYLIST_STORE.get<PlaylistData>('playlists', 'json')
    const apis: ApiConfig[] = []
    if (legacyData) {
      const id = generateId()
      apis.push({ id, name: 'VRChat Playlist', type: 'playlist', url: 'playlists', createdAt: new Date().toISOString() })
      await c.env.PLAYLIST_STORE.put(`data:${id}`, JSON.stringify(legacyData))
    }
    registry = { apis }
    await c.env.PLAYLIST_STORE.put('api_registry', JSON.stringify(registry))
  }

  return c.json(registry)
})

app.post('/admin/apis', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  const body = await c.req.json<{ name: string; type: 'playlist'; url: string }>()
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }

  if (registry.apis.some(a => a.url === body.url))
    return c.json({ error: 'URL already in use' }, 409)

  const newApi: ApiConfig = {
    id: generateId(),
    name: body.name,
    type: body.type,
    url: body.url,
    createdAt: new Date().toISOString(),
  }
  registry.apis.push(newApi)
  await c.env.PLAYLIST_STORE.put('api_registry', JSON.stringify(registry))
  await c.env.PLAYLIST_STORE.put(`data:${newApi.id}`, JSON.stringify({ playlists: [] }))
  return c.json(newApi, 201)
})

app.get('/admin/apis/:id/data', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  const id = c.req.param('id')
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }
  if (!registry.apis.some(a => a.id === id)) return c.json({ error: 'Not found' }, 404)

  const data = await c.env.PLAYLIST_STORE.get(`data:${id}`, 'json')
  return c.json(data ?? { playlists: [] })
})

app.put('/admin/apis/:id/data', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  const id = c.req.param('id')
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }
  if (!registry.apis.some(a => a.id === id)) return c.json({ error: 'Not found' }, 404)

  const body = await c.req.json()
  await c.env.PLAYLIST_STORE.put(`data:${id}`, JSON.stringify(body))
  return c.json({ ok: true })
})

app.delete('/admin/apis/:id', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  const id = c.req.param('id')
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }
  if (!registry.apis.some(a => a.id === id)) return c.json({ error: 'Not found' }, 404)

  registry.apis = registry.apis.filter(a => a.id !== id)
  await c.env.PLAYLIST_STORE.put('api_registry', JSON.stringify(registry))
  await c.env.PLAYLIST_STORE.delete(`data:${id}`)
  return c.json({ ok: true })
})

// ── Health routes ──────────────────────────────────────────────────
// POST is called once a day by a private iOS app forwarding Apple Health data.
// GET is fetched by the VRChat world via VRCDownloadString (no auth, read-only).

function roundMetric(metric: HealthMetric, value: number): number {
  const decimals = metric === 'weight' || metric === 'body_fat' ? 1 : 0
  const factor = 10 ** decimals
  return Math.round(value * factor) / factor
}

app.post('/api/health', async (c) => {
  if (!authed(c.env.HEALTH_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  let body: { days?: HealthDay[] }
  try {
    body = await c.req.json()
  } catch {
    return c.json({ error: 'Invalid JSON body' }, 400)
  }

  if (!Array.isArray(body.days) || body.days.length === 0)
    return c.json({ error: '"days" must be a non-empty array' }, 400)
  if (body.days.length > MAX_HEALTH_DAYS_PER_REQUEST)
    return c.json({ error: `"days" must not exceed ${MAX_HEALTH_DAYS_PER_REQUEST} entries` }, 400)

  const statements: D1PreparedStatement[] = []
  const upsert = c.env.HEALTH_DB.prepare(
    'INSERT INTO health_records (date, metric, value) VALUES (?, ?, ?) ' +
    'ON CONFLICT(date, metric) DO UPDATE SET value = excluded.value'
  )

  for (const day of body.days) {
    if (typeof day.date !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(day.date))
      return c.json({ error: `Invalid date: ${JSON.stringify(day.date)}` }, 400)

    for (const metric of HEALTH_METRICS) {
      const value = day[metric]
      if (value === undefined) continue
      if (typeof value !== 'number' || !Number.isFinite(value))
        return c.json({ error: `Invalid value for ${metric} on ${day.date}` }, 400)
      statements.push(upsert.bind(day.date, metric, value))
    }
  }

  if (statements.length > 0) await c.env.HEALTH_DB.batch(statements)

  return c.json({ ok: true, days: body.days.length, records: statements.length })
})

app.get('/api/health/data.json', async (c) => {
  const recentDates = await c.env.HEALTH_DB.prepare(
    'SELECT DISTINCT date FROM health_records ORDER BY date DESC LIMIT ?'
  ).bind(HEALTH_PUBLIC_DAYS).all<{ date: string }>()

  if (recentDates.results.length === 0)
    return c.json({ updated: new Date().toISOString(), days: [] })

  const cutoff = recentDates.results[recentDates.results.length - 1].date
  const rows = await c.env.HEALTH_DB.prepare(
    'SELECT date, metric, value FROM health_records WHERE date >= ? ORDER BY date ASC'
  ).bind(cutoff).all<{ date: string; metric: HealthMetric; value: number }>()

  const byDate = new Map<string, HealthDay>()
  for (const row of rows.results) {
    if (!byDate.has(row.date)) byDate.set(row.date, { date: row.date })
    byDate.get(row.date)![row.metric] = roundMetric(row.metric, row.value)
  }

  const days = [...byDate.values()].map((day) => {
    const out: HealthDay = { date: day.date }
    for (const metric of HEALTH_METRICS) {
      if (day[metric] !== undefined) out[metric] = day[metric]
    }
    return out
  })

  return c.json({ updated: new Date().toISOString(), days })
})

// ── Public dynamic route ─────────────────────────────────────────
// Matches any /:url slug registered in api_registry.

app.get('/:url', async (c) => {
  const urlParam = c.req.param('url')
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }
  const apiConfig = registry.apis.find(a => a.url === urlParam)

  if (!apiConfig) {
    // Legacy fallback: serve from old 'playlists' key before migration
    if (urlParam === 'playlists') {
      const data = await c.env.PLAYLIST_STORE.get<PlaylistData>('playlists', 'json')
      return c.json(data ?? { playlists: [] })
    }
    return c.json({ error: 'Not found' }, 404)
  }

  const data = await c.env.PLAYLIST_STORE.get(`data:${apiConfig.id}`, 'json')
  return c.json(data ?? { playlists: [] })
})

export default app
