import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { renderer } from './renderer'

type Track = { title: string; url: string }
type Playlist = { name: string; tracks: Track[] }
type PlaylistData = { playlists: Playlist[] }

type ApiConfig = {
  id: string
  name: string
  type: 'playlist'
  url: string
  createdAt: string
}
type ApiRegistry = { apis: ApiConfig[] }

// CloudflareBindings is auto-generated by `wrangler types`.
// PLAYLIST_AUTH_TOKEN is a Workers Secret — set via `wrangler secret put`.
type AppBindings = CloudflareBindings & { PLAYLIST_AUTH_TOKEN?: string }

const app = new Hono<{ Bindings: AppBindings }>()

app.use(renderer)
app.use('*', cors({ origin: '*', allowMethods: ['GET', 'PUT', 'POST', 'DELETE', 'OPTIONS'] }))

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 6)
}

function authed(secret: string | undefined, auth: string | null | undefined): boolean {
  return !!secret && auth === `Bearer ${secret}`
}

// ── System routes ─────────────────────────────────────────────────

app.get('/', (c) => c.render(<h1>Hello!</h1>))
app.get('/status', (c) => c.json({ message: 'Hello VRChat', updatedAt: new Date().toISOString() }))

// ── Admin routes (auth required) ──────────────────────────────────

app.get('/admin/apis', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  let registry = await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')

  if (!registry) {
    // First access: auto-migrate legacy playlist data if it exists
    const legacyData = await c.env.PLAYLIST_STORE.get<PlaylistData>('playlists', 'json')
    const apis: ApiConfig[] = []
    if (legacyData) {
      const id = generateId()
      apis.push({ id, name: 'VRChat Playlist', type: 'playlist', url: 'playlists', createdAt: new Date().toISOString() })
      await c.env.PLAYLIST_STORE.put(`data:${id}`, JSON.stringify(legacyData))
    }
    registry = { apis }
    await c.env.PLAYLIST_STORE.put('api_registry', JSON.stringify(registry))
  }

  return c.json(registry)
})

app.post('/admin/apis', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  const body = await c.req.json<{ name: string; type: 'playlist'; url: string }>()
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }

  if (registry.apis.some(a => a.url === body.url))
    return c.json({ error: 'URL already in use' }, 409)

  const newApi: ApiConfig = {
    id: generateId(),
    name: body.name,
    type: body.type,
    url: body.url,
    createdAt: new Date().toISOString(),
  }
  registry.apis.push(newApi)
  await c.env.PLAYLIST_STORE.put('api_registry', JSON.stringify(registry))
  await c.env.PLAYLIST_STORE.put(`data:${newApi.id}`, JSON.stringify({ playlists: [] }))
  return c.json(newApi, 201)
})

app.get('/admin/apis/:id/data', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  const id = c.req.param('id')
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }
  if (!registry.apis.some(a => a.id === id)) return c.json({ error: 'Not found' }, 404)

  const data = await c.env.PLAYLIST_STORE.get(`data:${id}`, 'json')
  return c.json(data ?? { playlists: [] })
})

app.put('/admin/apis/:id/data', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  const id = c.req.param('id')
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }
  if (!registry.apis.some(a => a.id === id)) return c.json({ error: 'Not found' }, 404)

  const body = await c.req.json()
  await c.env.PLAYLIST_STORE.put(`data:${id}`, JSON.stringify(body))
  return c.json({ ok: true })
})

app.delete('/admin/apis/:id', async (c) => {
  if (!authed(c.env.PLAYLIST_AUTH_TOKEN, c.req.header('Authorization')))
    return c.json({ error: 'Unauthorized' }, 401)

  const id = c.req.param('id')
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }
  if (!registry.apis.some(a => a.id === id)) return c.json({ error: 'Not found' }, 404)

  registry.apis = registry.apis.filter(a => a.id !== id)
  await c.env.PLAYLIST_STORE.put('api_registry', JSON.stringify(registry))
  await c.env.PLAYLIST_STORE.delete(`data:${id}`)
  return c.json({ ok: true })
})

// ── Public dynamic route ─────────────────────────────────────────
// Matches any /:url slug registered in api_registry.

app.get('/:url', async (c) => {
  const urlParam = c.req.param('url')
  const registry = (await c.env.PLAYLIST_STORE.get<ApiRegistry>('api_registry', 'json')) ?? { apis: [] }
  const apiConfig = registry.apis.find(a => a.url === urlParam)

  if (!apiConfig) {
    // Legacy fallback: serve from old 'playlists' key before migration
    if (urlParam === 'playlists') {
      const data = await c.env.PLAYLIST_STORE.get<PlaylistData>('playlists', 'json')
      return c.json(data ?? { playlists: [] })
    }
    return c.json({ error: 'Not found' }, 404)
  }

  const data = await c.env.PLAYLIST_STORE.get(`data:${apiConfig.id}`, 'json')
  return c.json(data ?? { playlists: [] })
})

export default app
